# Generated by Django 5.2 on 2025-04-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cloth_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категорий'},
        ),
        migrations.AddField(
            model_name='category',
            name='full_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Mini name '),
        ),
    ]
