# Generated by Django 5.2 on 2025-04-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_options_category_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='prise',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='cloths',
            field=models.ManyToManyField(related_name='cloths', to='app.category'),
        ),
        migrations.CreateModel(
            name='Shop_Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cloth')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shop')),
            ],
        ),
    ]
