# Generated by Django 5.2 on 2025-04-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cloth_prise_shop_cloths_shop_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
