# Generated by Django 5.2 on 2025-04-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_shop_cloth_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cloth',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_clothes', to='app.shop'),
        ),
    ]
