# Generated by Django 5.2 on 2025-04-14 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_shop_cloth_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop_Cloth',
            new_name='ShopCloth',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='data',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='Create_Country',
            new_name='country_of_origin',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='data',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='cloths',
        ),
        migrations.AddField(
            model_name='shop',
            name='clothes',
            field=models.ManyToManyField(related_name='shops', through='app.ShopCloth', to='app.cloth'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Mini name'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='app.category'),
        ),
    ]
