# Generated by Django 5.2 on 2025-04-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_shop_cloth_shopcloth_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='clothes',
        ),
    ]
